apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dynamic-forms-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dynamic-forms
  minReplicas: 1
  maxReplicas: 10  # Ajusta esto según tus necesidades
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50  # Target CPU utilization percentage
